---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: prod
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgAW3zTwzWMR1Zya2Vu0y6kMGqE4n2j8IdkDn+wMizMD3BmV04Ra73wUW9jyORkeaQgjxqoaP3oBtNXnEjyJElwLJIXB/ofU7PvAbVmsaRBnf0VKVSQXs8t6VvULs9N5KHIzwG+/wJhwpYVQzLfFZrmOiOPMkeYBL7PYx7yq7DXZ0CZhVXf5mfGWmsB3zF8Vckztu3fUKSxLiZcuAGnFmx4gMvmfD+//GUjEKOy7NduEe4UexBe9fIVIletpYGdi2yJFBj8WLmxQBXvo+P5x2SVEHNRL7TwFzw0qxP0rin0rjE7yP8Tef3uVvWKKJjNvSSkVd+1KZEdprFIJvw8hO13LJ2tjJrSvquBxBXZrMVbJx61boZvU7AGBLxQXWWXTlhVdDvXiKtiBDBA1zAbJ29AO4dD8znewC0ZmpmeYnSqOtugkWGnR/zU15J8NSuuPwmzy4VB4noS89GKqwenvYnFMwXCZ4b+tNaGQmXZV9M9wxr6OjS7ssug2pVl0B335hiSK26g3hjhdgvxdo+Sao4mAMJQEkYCSkxdUUqe1ujbGbjJSOT+AQ53IWwgIfQxJAioXSL9rql58U75Z7yVDrXLYlrIPhK24UW7QM8T0XhRadasRZOP02j0G9o7LNZdbmFp8vpCGRG9ZZ63347JLjro2jaJPlIiaCE81zxv8AuZY5vzYt2pqi282Oakn3Cp3CRZNnjk7kcg6O1SRWMXG0uqV4RmVUA==
    AWS_SECRET_KEY: AgAEozCHxfTJhrdr71HnJ3BnSv0q9epqSA0YSLdmTNdcnGbJ590/0W7Ew7EyAqR9w16wuTSV8aJT+tdQCzaRq5zN8BGqT/H8yv/YU/Pv7mHRdIp0cebzogoRzrblDnmotcYUEuTPmlv8Os/BAVa48p6kLs0KNb8VezpwqvCf2EdUJOL1sJiJg7ZuNBpNGDhvGBG2Vve7Oy5JulBiVfM28wRVIrBIZ/MgJiLYpz1Ls4RO5fkc3Bm2BCubtXAJPwjRvPcsgWCzpNgVMYRkeqEYB/wk/jJlLNdRoEKV5NUkvOY9KmZ9G1DGvxQCSbcWSAiT+/5Rt6wIT8QpF0kD67nqfe5L0LNNFAS2PNwNMUc6RiGoMBwxL79icVTAFeNktDLegyL40xOl+uK2uovQK5fAE0dsoA31B8XhI02acaj0CsstnLrrobtyKTSsM/MllOGYAY1FlAg0ogF2hi6ZAFGlOEST/xDH/k9+/k4YUu5ns42KKIVJq00RoegiTAmp+zI4ZY9XTM7NPZkjA+1uee32DzCMyNRna9rU/Zr4azhCkHDRO//tckc2/bUpfKzA0twS/3NRZOVeGN5T1e0bfAjpDXPTuvpHoYD9qPftPs+Je9fJLM7/yrhbqJeUhp65IKMtw1Q1vLePC0M4qhOpVG9c5fbtQNlg8iHN/R+pYV7XWzMpb00bM5Pd5b8+0/hrRmSdvuF3trBu/TdITOkL7z9nchFE1WIqZaB230/OXe7kh2ZFTxx5hwub72JU
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: prod
