---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: prod
spec:
  encryptedData:
    AWS_ACCESS_KEY: AgAH7YLIiA42ItPoLTpp6d3wf2LFjS7CnlgP0BRrmmqjm1Zym1LTe9rexg0cnSTqn6m8cHkoHyt8xUHLlieZAwiQY+kw/j1aex0lkdrO5o1WeK30uUZqtRrCozmql3ZCWqAUBlopxUfmdXTDOXA/rkU8t7zLczS/4q6fmVPdJ6OdxCriM4AFpIiGBKRnq3ljLLSXK7cY56voz3s6eIQIhKEOEA14hUddL3zdU6Csy20PZtxB9f5nYBKfokuQrbLKn8BlwSG/tLklc/eFIuBazmjLIG3LOxFYwmq43jJPut0NUPGgSHDP+Av5v9HNahn1Dlg4woabCkX+M/DZVfNVbr8Xo1tpRavY2IXcFR8Jel0aG6MvIq9R8zmoEikxNwqDnZm40eJj4Pdy5F56MkO2wRNzhZSwFjS1Se5SUFdX9Xc6HidsnVNPs4OrG28McEpj0fsl7DcW76+5rRw8BYwiQIE3EP06ANKNYWdnTQAFTNlZzii8RT9YVwG5QbwTFdcRXp0RWBoFPOkAwTc+Qsv8ZNI/OLGTyjj6DhUKZL5rQ47/3pgXyELcm7rsbvPS9KTlqofJpMmQ7Aeu9NGJzgilScJiwn7NrKgxarcNNirjUfiTaXrBfOS59igDc4YJX53tkdkxs2CNv2EluIoMTrDSSTA2OzPqTpw2KD+O7jT2LJFQ6K/NhKsOpUJmNQRr1xkxs6J9pQBsdHQ329CTJ7QH0wgdcC+JzA==
    AWS_SECRET_KEY: AgAnq2WKTDTaTIhbFdNoa+AMugjhUbQOTqu1qI2ufGTbxG3AVB5xE2uEGsdCYRjUD8kYfCQxstSeGJYhPW8ghrTMDzUUmMF++dvsM93Q6lhevq4ZUhhcOuXPPGwiWzLIuMJM/WvO3fxKait8kkeeUWTVf996E77pcGmf5Zb9ARb2JMfnmrkw3I66TP9uoDlja8/rWYdkcEm6NK83wJg5+JV4dPQFVh4DW30Dl3+VilM9FsiiAznQg2+SaK+YTv/wcDUKzh4XzV1YioQm15VufOVIbJVKOhDrdl2Ri2CxaX9CQviDzN+YlmYkspAcezdcJwwJwV5YlomQdH12mQFdpVlPjXON5GWG+lUtlEyMPIUgFFtq6lKwhgd340PZw7NvkOVEixeg4F5tvUj5b2rGr7qgl0V7QDuPpgDX4wV0zhvQ3QiUyo8TCV5ZyFQ4NKtrNJS/9BmLo9ZMkQ5jN5mOxvXzpBZXumtdkz+xr2u2Sc+v2aHhYXsMcJtt8bMhe4rznf0Plv5xeIOWGMWn8LjJIfxh6CCzK6wxIHjOJfBv7RPygHsqHHt0rkdIsEtZMjzsE14qZjAG5yIb/o4NyITzePCvfE1Fnjh4iNb0+fttqjIOeUaNROYPhPsGvwl3hiQVuvqIOscjG/g1sueC35OVzVRhlGs03SY7oDbbedTCSermiLxxvZj0dOXUn8V8yeuLsMlIgYKmaRTY2A5B8qxdHRvIyyc5QvBiEpvWI+kT5L0J+fcuaikb2xH0
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: prod
